version: '3.4'

services:
  db:
    image: finance/personal/db/image
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1444:1433"
    volumes:
      - mssqldata:/var/opt/mssql

volumes:
  mssqldata: